name: Test and Lint

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest vivarium_cytosim/tests/

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        flake8 vivarium_cytosim --count --verbose --show-source --statistics
    - name: Check with black
      shell: bash -l {0}
      run: |
        black --check vivarium_cytosim
